### PR TITLE
Add io.github.mpc_qt.mpc-qt

### PR DESCRIPTION
**Pull request by tbertels**
### Please confirm your submission meets all the criteria

- [X] Please describe the application briefly. Media Player Classic Qute Theater (MPC-QT) is a media player based on libmpv.
- [X] The domain used for the application ID is [controlled by the application developer(s)][appid-domain] and the [application id guidelines][appid] are followed.
- [X] I have read and followed all the [Submission requirements][reqs] and the [Submission guide][reqs2].
- [X] I have [built][build] and tested the submission locally.
- [X] I am an author/developer/upstream contributor to the project. If not, I contacted upstream developers about this submission. **Link:**

@cmdrkotori (made a previous PR #2888)

[appid-domain]: https://docs.flathub.org/docs/for-app-authors/requirements/#control-over-domain-or-repository
[appid]: https://docs.flathub.org/docs/for-app-authors/requirements#application-id
[reqs]: https://docs.flathub.org/docs/for-app-authors/requirements
[reqs2]: https://docs.flathub.org/docs/for-app-authors/submission
[build]: https://docs.flathub.org/docs/for-app-authors/submission/#before-submission

### CODE REVIEW

**Comment by tbertels** [comment]
bot, build io.github.mpc_qt.mpc-qt

File: io.github.mpc_qt.mpc-qt.yml [hunk 1]
```diff
@@ -0,0 +1,294 @@
+app-id: io.github.mpc_qt.mpc-qt
+runtime: org.kde.Platform
+runtime-version: '6.7'
```
Comment (hfiguiere) [inline io.github.mpc_qt.mpc-qt.yml:3]: current is 6.8

File: io.github.mpc_qt.mpc-qt.yml [hunk 2]
```diff
@@ -0,0 +1,294 @@
...
+              - type: archive
+                url: https://github.com/FFmpeg/nv-codec-headers/archive/refs/tags/n13.0.19.0.tar.gz
+                sha256: 86d15d1a7c0ac73a0eafdfc57bebfeba7da8264595bf531cf4d8db1c22940116
+                x-checker-data:
+                  type: anitya
+                  project-id: 223796
+                  stable-only: true
+                  url-template: https://github.com/FFmpeg/nv-codec-headers/archive/refs/tags/n$version.tar.gz
+
+          - name: ffmpeg
```
Comment (hfiguiere) [inline io.github.mpc_qt.mpc-qt.yml:188]: why not using the ffmpeg from the runtime?

File: io.github.mpc_qt.mpc-qt.yml [hunk 3]
```diff
@@ -0,0 +1,294 @@
...
+              - type: archive
+                url: https://ffmpeg.org/releases/ffmpeg-7.1.tar.gz
+                sha256: 42a7dc0d1583885d1b8f6559fa7ce28f97acafea6803de6a8f73e3ba229348bd
+                x-checker-data:
+                  type: anitya
+                  project-id: 5405
+                  stable-only: true
+                  url-template: https://ffmpeg.org/releases/ffmpeg-$version.tar.gz
+            modules:
+              - name: libjxl
```
Comment (hfiguiere) [inline io.github.mpc_qt.mpc-qt.yml:226]: this is in the runtime.

File: io.github.mpc_qt.mpc-qt.yml (hunk 1 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:3]: With 6.8, mpv didn't build, with the same error as in https://github.com/terrapkg/packages/issues/3338.

Comment (hfiguiere) [reply io.github.mpc_qt.mpc-qt.yml:3]: then you need to figure out why. 6.7 will be EOL soon enough.

File: io.github.mpc_qt.mpc-qt.yml [hunk 4]
```diff
@@ -0,0 +1,294 @@
...
+sdk: org.kde.Sdk
+command: mpc-qt
+rename-icon: mpc-qt
+copy-icon: true
+finish-args:
+  - --share=ipc
+  - --share=network
+# We support both Xwayland and Wayland because Wayland doesn't allow resizing the window
+  - --socket=x11
+  - --socket=wayland
```
[the remark this answers is not in the document]
Comment (hfiguiere) [reply io.github.mpc_qt.mpc-qt.yml:13]: There is no option. If it support wayland, use that (with the fallback when there is no wayland). That's the build failure btw.

File: io.github.mpc_qt.mpc-qt.yml (hunk 2 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:188]: h265 didn't work and h264 didn't have hardware accelerated decoding.

Comment (hfiguiere) [reply io.github.mpc_qt.mpc-qt.yml:188]: you need the ffmpeg-full extension it has h265 support.

File: io.github.mpc_qt.mpc-qt.yml (hunk 3 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:226]: ffmpeg didn't build without it.

Comment (hfiguiere) [reply io.github.mpc_qt.mpc-qt.yml:226]: it is in the 6.8 runtime, not in the older one. Use 6.8

Comment (hfiguiere) [reply io.github.mpc_qt.mpc-qt.yml:226]: and likely you don't need to build ffmpeg anyway.

File: io.github.mpc_qt.mpc-qt.yml (hunk 4 above)
[the remark this answers is not in the document]
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:13]: I mean there's an option in the settings of the app. How does [mpv](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml) build with that?

File: io.github.mpc_qt.mpc-qt.yml (hunk 3 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:226]: OK, thanks! I'm trying a build with 6.8 and ffmpeg-full.

Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:226]: Unfortunately, same problem as before with 6.8 and ffmpeg-full: no h265 decoding and no h264 hardware decoding.

Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:226]: Haruna doesn't use the ffmpeg-full (or ffmpeg) extension either: https://github.com/flathub/org.kde.haruna/blob/master/org.kde.haruna.yml

Comment (hfiguiere) [reply io.github.mpc_qt.mpc-qt.yml:226]: two wrongs don't make a right.

File: io.github.mpc_qt.mpc-qt.yml (hunk 1 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:3]: I was hoping that error (`x86_64-unknown-linux-gnu/bin/ld: /app/lib/libmpv.so: undefined reference to av_dovi_find_level@LIBAVUTIL_59`) will get fixed some time in the future.

Comment (hfiguiere) [reply io.github.mpc_qt.mpc-qt.yml:3]: that looks like it's linking against the wrong version. There is a ffmpeg in the runtime too. 

it's not the runtime's fault.

File: io.github.mpc_qt.mpc-qt.yml (hunk 3 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:226]: Well, I couldn't find a libmpv-based player which uses successfully that extension. I've used the manifests of Haruna and [Memento](https://github.com/flathub/io.github.ripose_jp.Memento/blob/master/io.github.ripose_jp.Memento.yml) to make this one.

Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml:226]: I've tried with `org.kde.Platform` `6.8` with the extension `org.freedesktop.Platform.ffmpeg-full` `24.08`.

File: io.github.mpc_qt.mpc-qt.yml (hunk 1 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml]: Downgrading ffmpeg to 7.0.2 (which includes libavutil 59.8.100 instead of 59.39.100) fixes it.
Hopefully the org.kde.Platform 6.9 will work with ffmpeg 7.1.
h265 decoding (and hardware h264 decoding) may even [work out of the box](https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/67) with libmpv.

**Comment by tbertels** [comment]
bot, build io.github.mpc_qt.mpc-qt

File: io.github.mpc_qt.mpc-qt.yml (hunk 1 above)
Comment (tbertels) [reply io.github.mpc_qt.mpc-qt.yml]: Well, it fixes the build, but then h265 decoding (and hardware h264 decoding) don't work either. So I'm guessing org.freedesktop.Platform.ffmpeg-full 24.08 uses ffmpeg 7.0.2.
Hopefully, 25.08 will use ffmpeg 7.1 and work with libmpv.

Comment (bbhtt) [reply io.github.mpc_qt.mpc-qt.yml]: > Downgrading ffmpeg to 7.0.2 (which includes libavutil 59.8.100 instead of 59.39.100) fixes it.

6.8 uses that exact same version 7.0.2

File: io.github.mpc_qt.mpc-qt.yml (hunk 4 above)
[the remark this answers is not in the document]
Comment (bbhtt) [reply io.github.mpc_qt.mpc-qt.yml:13]: It either supports wayland by default or doesn't, in betweens are unsupported.

File: io.github.mpc_qt.mpc-qt.yml (hunk 2 above)
Comment (bbhtt) [reply io.github.mpc_qt.mpc-qt.yml:188]: this exact version of ffmpeg is in the runtime and ffmpeg-full in 6.8

File: io.github.mpc_qt.mpc-qt.yml (hunk 3 above)
Comment (bbhtt) [reply io.github.mpc_qt.mpc-qt.yml:226]: > Well, I couldn't find a libmpv-based player which uses successfully that extension. I've used the manifests of Haruna and [Memento](https://github.com/flathub/io.github.ripose_jp.Memento/blob/master/io.github.ripose_jp.Memento.yml) to make this one.

https://github.com/flathub/io.github.hydrusnetwork.hydrus/blob/949af31813e1700c7daf2fd9591ef112384a333d/io.github.hydrusnetwork.hydrus.yml#L10-L14



https://github.com/flathub/com.github.rafostar.Clapper/blob/f58477c35674f49aedc343c25d227f40eecf92f7/com.github.rafostar.Clapper.json#L7-L8

**Comment by tbertels** [comment]
bot, build io.github.mpc_qt.mpc-qt

**Comment by tbertels** [comment]
bot, build io.github.mpc_qt.mpc-qt

**Comment by tbertels** [comment]
bot, build io.github.mpc_qt.mpc-qt
